prepare CI further, add requirements and main.py

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,14 @@ jobs:
         sudo apt-get install gfortran libopenblas-dev liblapack-dev
         sudo apt install python3 python3-pip python3-numpy python3-scipy
     - run: |
-        sudo python3 -m pip install -r requirements_ci.txt
+        sudo python3 -m pip install -r requirements.txt
     - run: |
-        pwd
+        python3 src/main.py -i test/short.txt -o test/short_out.txt
+        diff test/short_out.txt test/short.txt
+        if [ $? -eq 0 ]; then
+          echo "Test passed"
+        else
+          echo "Test failed"
+          exit 1
+        fi
+        sudo rm test/short_out.txt
